// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // read directly instead of prisma/config's `env()`, which throws the moment this file loads.
  // `generate` and `validate` are offline commands that only need a syntactically valid URL,
  // and they have to run where no database is configured — a CI runner, a Vercel build. The
  // commands that actually connect fail on their own against this placeholder.
  datasource: {
    url: process.env.DATABASE_URL ?? "postgresql://unset:unset@localhost:5432/unset",
  },
});
